##Conclusion Grafikz
library(dplyr)

##GSADF-Panel

library(readxl)
Eins <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Australien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Eins$ID <- c(rep(1))
Zwei <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Belgien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Zwei$ID <- c(rep(2))
Drei <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Chile.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Drei$ID <- c(rep(3))
Vier <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Daenemark.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Vier$ID <- c(rep(4))
Funf <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Deutschland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Funf$ID <- c(rep(5))
Sechs <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_England.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Sechs$ID <- c(rep(6))
Sieben <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Estland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Sieben$ID <- c(rep(7))
Acht <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Finnland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Acht$ID <- c(rep(8))
Neun <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Frankreich.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Neun$ID <- c(rep(9))
Zehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Griechenland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Zehn$ID <- c(rep(10))
Elf <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Irland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Elf$ID <- c(rep(11))
Zwolf <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Island.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Zwolf$ID <- c(rep(12))
Dreizehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Israel.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Dreizehn$ID <- c(rep(13))
Vierzehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Italien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Vierzehn$ID <- c(rep(14))
Funfzehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Japan.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Funfzehn$ID <- c(rep(15))
Sechszehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Kanada.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Sechszehn$ID <- c(rep(16))
Siebzehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Kolumbien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Siebzehn$ID <- c(rep(17))
Achtzehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Korea.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Achtzehn$ID <- c(rep(18))
Neunzehn <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Lettland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Neunzehn$ID <- c(rep(19))
Zwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Litauen.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Zwanzig$ID <- c(rep(20))
Einundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Luxenburg.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Einundzwanzig$ID <- c(rep(21))
Zweiundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Mexiko.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Zweiundzwanzig$ID <- c(rep(22))
Dreiundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Neuseeland.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Dreiundzwanzig$ID <- c(rep(23))
Vierundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Niederlande.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Vierundzwanzig$ID <- c(rep(24))
Funfundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Norwegen.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Funfundzwanzig$ID <- c(rep(25))
Sechsundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Österreich.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Sechsundzwanzig$ID <- c(rep(26))
Siebenundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Polen.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Siebenundzwanzig$ID <- c(rep(27))
Achtundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Portugal.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Achtundzwanzig$ID <- c(rep(28))
Neunundzwanzig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Schweden.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Neunundzwanzig$ID <- c(rep(29))
Dreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Schweitz.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Dreisig$ID <- c(rep(30))
Einunddreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Slowakai.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Einunddreisig$ID <- c(rep(31))
Zweiunddreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Slowenien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Zweiunddreisig$ID <- c(rep(32))
Dreiunddreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Spanien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Dreiunddreisig$ID <- c(rep(33))
Vierunddreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Tschechien.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Vierunddreisig$ID <- c(rep(34))
Funfunddreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Türkei.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Funfunddreisig$ID <- c(rep(35))
Sechsunddreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_Ungarn.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Sechsunddreisig$ID <- c(rep(36))
Siebenundreisig <- read_excel("C:/Users/Felix/OneDrive - Universität Hamburg/Studium VWL UHH/Semester 6/Bachelorarbeit/Daten/GSADF/GSADF_USA.xlsx",col_types = c("date", "skip", "skip", "skip", "skip", "numeric", "skip"))
Siebenundreisig$ID <- c(rep(37))

list <- c(Eins, Zwei, Drei, Vier, Funf, Sechs, Sieben, Acht, Neun, Zehn, Elf, Zwolf, Dreizehn, Vierzehn, Funfzehn, Sechszehn, Siebzehn, Achtzehn, Neunzehn, Zwanzig, Einundzwanzig, Zweiundzwanzig, Dreiundzwanzig, Vierundzwanzig, Funfundzwanzig, Sechsundzwanzig, Siebenundzwanzig, Achtundzwanzig, Neunundzwanzig, Dreisig, Einunddreisig, Zweiunddreisig, Dreiunddreisig, Vierunddreisig, Funfunddreisig, Sechsunddreisig, Siebenundreisig)

jack <- c(rep(0))

i = 2

while (i < 110){
  t = length(list[[i]])
  if (list[[i]][t] == 1){
    jack = append(jack,list[[i+1]][t])
  }
  i = i+3
}

rm(list = ls()) 
