#Additional function required for plotting
match_logical <- function(x){
  
  x <- as.character(x)
  
  out <- try(grepl(pattern = "T", x = x, ignore.case = T))
  
  if(class(out) == "try-error"){
    stop("Please pass a logical (i.e. TRUE or FALSE)")
  }
  
  out
}

#New function allowing to use dates as dates instead of numbers
plot_placebos_modify <- function (tdf = tdf, discard.extreme = FALSE, mspe.limit = 20, 
          xlab = NULL, ylab = NULL, title = NULL, alpha.placebos = 1, 
          ...) 
{
  year <- cont <- id <- Y1 <- synthetic.Y1 <- NULL
  if (!is_tdf(tdf)) {
    stop("Please pass a valid `tdf` object the tdf argument.\nThese are generated by the `generate.placebos` function.")
  }
  discard.extreme <- match_logical(discard.extreme)
  if (!discard.extreme & mspe.limit != 20) {
    warning("discard.extreme is FALSE. mspe.limit will be ignored.")
  }
  n <- tdf$n
  t1 <- as.Date(unique(tdf$df$year)[which(tdf$df$year == tdf$t1) - 
                              1])
  tr <- tdf$tr
  names.and.numbers <- tdf$names.and.numbers
  treated.name <- as.character(tdf$treated.name)
  df.plot <- NULL
  for (i in 1:n) {
    a <- cbind(as.Date(tdf$df$year), tdf$df[, i], tdf$df[, n + i], 
               i)
    df.plot <- rbind(df.plot, a)
  }
  df.plot <- data.frame(df.plot)
  colnames(df.plot) <- c("year", "cont", "tr", "id")
  if (discard.extreme) {
    df.plot <- df.plot[!df.plot$id %in% which(tdf$mspe.placs/tdf$loss.v[1] >= 
                                                mspe.limit), ]
  }
  else {
    df.plot <- df.plot
  }
  p.gaps <- ggplot2::ggplot(data = data.frame(df.plot), ggplot2::aes(x = rep(years,22), 
                                                                     y = (tr - cont))) + ggplot2::geom_line(ggplot2::aes(group = id, 
                                                                                                                         color = "2")) + ggplot2::geom_vline(xintercept = myt1, 
                                                                                                                                                             linetype = "dotted") + ggplot2::geom_hline(yintercept = 0, 
                                                                                                                                                                                                        linetype = "dashed") + ggplot2::geom_line(data = data.frame(tdf$df), 
                                                                                                                                                                                                                                                  ggplot2::aes(x = year, y = (Y1 - synthetic.Y1), color = "1"), 
                                                                                                                                                                                                                                                  alpha = alpha.placebos) + ggplot2::ylim(c(1.5 * min(c(min(tdf$df$Y1 - 
                                                                                                                                                                                                                                                                                                              tdf$df$synthetic.Y1), min(df.plot$tr - df.plot$cont))), 
                                                                                                                                                                                                                                                                                            1.5 * max(c(max(tdf$df$Y1 - tdf$df$synthetic.Y1), max(df.plot$tr - 
                                                                                                                                                                                                                                                                                                                                                    df.plot$cont))))) + ggplot2::labs(y = ylab, x = xlab, 
                                                                                                                                                                                                                                                                                                                                                                                      title = title) + ggplot2::scale_color_manual(values = c(`2` = "gray80", 
                                                                                                                                                                                                                                                                                                                                                                                                                                              `1` = "black"), labels = c("Control units", tdf$treated.name), 
                                                                                                                                                                                                                                                                                                                                                                                                                                   guide = ggplot2::guide_legend(NULL)) + ggplot2::theme(panel.background = ggplot2::element_blank(), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         axis.line.x = ggplot2::element_line(colour = "black"), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         axis.line.y = ggplot2::element_line(colour = "black"), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         legend.key = ggplot2::element_blank(), axis.text.x = ggplot2::element_text(colour = "black"), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         axis.text.y = ggplot2::element_text(colour = "black"), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         legend.position = "bottom")
  return(p.gaps)
}

